### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by shikaichao-hub** [MasterBin-IIAU/CSA#2]
Hello, I follow the steps in the readme file to run the run_search_adv0.py ,but I find a error.
![mmexport1615724936162](https://user-images.githubusercontent.com/65749168/111068533-18f4ec80-8504-11eb-9321-68e854cc09d0.jpg).Could you help me solve this problem?

**Comment by MasterBin-IIAU** [comment]
Hi, it seems to be the problem with the environment variable PYTHONPATH.
As shown in README, we need to add the following paths to the PYTHONPATH

export PYTHONPATH=<CSA_PATH>:$PYTHONPATH
export PYTHONPATH=<CSA_PATH>/pysot:$PYTHONPATH
export PYTHONPATH=<CSA_PATH>/pix2pix:$PYTHONPATH

Note that <CSA_PATH> should be replaced with the real path on your computer. And we recommend running the code on Linux rather than WINDOWS.
